# fly.toml app configuration file generated for assist-bot on 2025-07-19T20:48:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assist-bot'
primary_region = 'lax'

[build]

[deploy]

[env]
  PIPEDREAM_ENVIRONMENT = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
